# Generated by Django 6.0.1 on 2026-02-05 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique concept name (e.g., 'perspective', 'shading', 'anatomy')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('fundamentals', 'Fundamentals'), ('figure_drawing', 'Figure Drawing'), ('composition', 'Composition'), ('color_theory', 'Color Theory'), ('anatomy', 'Anatomy'), ('technique', 'Technique'), ('style', 'Style'), ('advanced', 'Advanced Concepts')], help_text='Broad category this concept belongs to', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Skill level required to learn this concept', max_length=20)),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text="List of concept names that should be learned before this one (e.g., ['basic_shapes', 'line_control'])")),
                ('description', models.TextField(help_text='Detailed description of what this concept teaches')),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text="List of specific learning objectives (e.g., ['Draw objects in 1-point perspective', 'Identify vanishing points'])")),
                ('related_concepts', models.JSONField(blank=True, default=list, help_text="List of related concept names that complement this one (e.g., ['light_source', 'values', 'contrast'])")),
                ('estimated_practice_hours', models.IntegerField(blank=True, help_text='Estimated hours needed to achieve proficiency', null=True)),
                ('common_mistakes', models.JSONField(blank=True, default=list, help_text='Common mistakes learners make with this concept')),
                ('tips_for_improvement', models.JSONField(blank=True, default=list, help_text='Tips and tricks for mastering this concept')),
                ('sample_exercise_prompts', models.JSONField(blank=True, default=list, help_text="Example exercise prompts AI can use or modify (e.g., ['Draw a cube in 2-point perspective', 'Shade a sphere with light from the left'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this concept is currently available for curriculum generation')),
                ('times_used', models.IntegerField(default=0, help_text='Number of times this concept has been included in curricula (for analytics)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concept Library',
                'ordering': ['category', 'difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text="User's current artistic skill level", max_length=20)),
                ('artistic_goal', models.TextField(blank=True, help_text="What the user wants to achieve (e.g., 'improve portraits', 'learn anime style')")),
                ('time_commitment', models.CharField(blank=True, choices=[('casual', 'Casual (1-2 hours/week)'), ('regular', 'Regular (3-5 hours/week)'), ('intensive', 'Intensive (5+ hours/week)')], help_text='How much time user can dedicate to learning', max_length=50, null=True)),
                ('preferred_styles', models.JSONField(blank=True, default=list, help_text="List of preferred art styles (e.g., ['realistic', 'anime', 'abstract'])")),
                ('has_completed_pretest', models.BooleanField(default=False, help_text='Whether user has completed initial assessment')),
                ('has_active_curriculum', models.BooleanField(default=False, help_text='Whether user has an AI-generated curriculum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
