# Generated by Django 6.0.2 on 2026-02-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_chatmessage_conceptmastery_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='curriculum.learninggoal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('figure_drawing', 'Figure Drawing'), ('composition', 'Composition'), ('color_theory', 'Color Theory'), ('anatomy', 'Anatomy'), ('technique', 'Technique'), ('style', 'Style'), ('advanced', 'Advanced Concepts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='estimated_practice_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='related_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='sample_exercise_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conceptlibrary',
            name='tips_for_improvement',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artistic_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_active_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_completed_pretest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_commitment',
            field=models.CharField(blank=True, choices=[('casual', 'Casual (1-2 hours/week)'), ('regular', 'Regular (3-5 hours/week)'), ('intensive', 'Intensive (5+ hours/week)')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('action', models.CharField(max_length=100)),
                ('change_made', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='curriculum.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PretestQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='curriculum.pretestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PretestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='curriculum.pretestquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_results', to='curriculum.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.userprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum.userprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum.section')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='curriculum.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='curriculum.userprofile')),
            ],
            options={
                'unique_together': {('user', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='curriculum.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='curriculum.userprofile')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
