# Generated by Django 6.0.2 on 2026-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('beginner-intermediate', 'Beginner-Intermediate'), ('intermediate', 'Intermediate'), ('intermediate-advanced', 'Intermediate-Advanced'), ('advanced', 'Advanced')], default='beginner', max_length=50),
        ),
    ]
