# Generated by Django 6.0.2 on 2026-04-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_gradereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
