# Generated by Django 6.0.2 on 2026-04-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_dashboard_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
