# Generated by Django 6.0.2 on 2026-04-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_dashboard_options_dashboard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
