# Generated by Django 6.0.2 on 2026-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_dashboard_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gesture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lifeDrawing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stillLife',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.IntegerField(default=0),
        ),
    ]
