# Generated by Django 6.0.2 on 2026-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_userprofile_gesture_userprofile_lifedrawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gesture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifeDrawing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stillLife',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FloatField(default=0),
        ),
    ]
