# Generated by Django 6.0.2 on 2026-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_userprofile_gesture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gesture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifeDrawing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stillLife',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
