# Generated by Django 6.0.2 on 2026-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_alter_userprofile_gesture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lifeDrawing',
            new_name='lifedrawing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stillLife',
            new_name='stilllife',
        ),
    ]
