# Generated by Django 6.0.2 on 2026-04-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_rename_lifedrawing_userprofile_lifedrawing_and_more'),
    ]

    operations = [
        # Clear non-JSON string feedback from old TextField rows before altering the column type
        migrations.RunSQL("UPDATE curriculum_gradereport SET feedback = 'null'"),
        migrations.AlterField(
            model_name='gradereport',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
